dist: trusty
sudo: false
git:
  depth: 1
language: php
matrix:
  fast_finish: true
  include:
  - php: 5.4
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.4
  - php: 5.5
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.5
  - php: 5.6
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 5.6
    env: PHPUNIT_COVERAGE="--coverage-clover=coverage.xml"
  - php: 7.0
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.0
  - php: 7.1
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: 7.1
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
  allow_failures:
  - php: nightly
    env: COMPOSER_LOWEST="--prefer-lowest"
  - php: nightly
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- stty cols 120
- |
  if [ -z "$PHPUNIT_COVERAGE" ]; then
      phpenv config-rm xdebug.ini || true
  fi
install:
- composer self-update
- composer config -g repositories.asset-packagist composer https://asset-packagist.org
- travis_retry composer update --no-interaction --prefer-stable --prefer-dist $COMPOSER_LOWEST
- composer show
script:
- vendor/bin/phpunit $PHPUNIT_COVERAGE
after_success:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://codecov.io/bash
      bash ./bash
  fi
after_script:
- |
  if [ -n "$PHPUNIT_COVERAGE" ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  fi
